tests
exampleCode01
^ 'com.fsck.k9.mail.AuthType,AuthType,Information Holder,enum
com.fsck.k9.mailstore.BinaryMemoryBody,BinaryMemoryBody,Information Holder,class
com.fsck.k9.mail.Address,Address,Service Provider,class
com.fsck.k9.mail.Authentication,Authentication,Service Provider,class
com.fsck.k9.mail.AuthenticationFailedException,AuthenticationFailedException,Information Holder,class
com.fsck.k9.mail.Body,Body,Service Provider,interface
com.fsck.k9.mail.BodyFactory,BodyFactory,Service Provider,interface
com.fsck.k9.mail.BodyPart,BodyPart,Information Holder,abstract class
com.fsck.k9.mail.BoundaryGenerator,BoundaryGenerator,Service Provider,class
com.fsck.k9.mail.CertificateChainException,CertificateChainException,Information Holder,class
com.fsck.k9.mail.CertificateValidationException.Reason,Reason,Information Holder,enum
com.fsck.k9.mail.CertificateValidationException,CertificateValidationException,Information Holder,class
com.fsck.k9.mail.ConnectionSecurity,ConnectionSecurity,Information Holder,enum
com.fsck.k9.mail.DefaultBodyFactory,DefaultBodyFactory,Service Provider,class'